import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { relative } from "node:path";
import process, { stdout } from "node:process";
import { fileURLToPath } from "node:url";

// Hash the source files that determine a page's rendered output, so the worker's
// PDF/OG cache key changes automatically when content changes — no manual bumps.
const OUTPUT_PATH = fileURLToPath(
	new URL("../src/worker/content-hashes.gen.ts", import.meta.url)
);

function resolveFromRoot(path: string) {
	return fileURLToPath(new URL(path, import.meta.url));
}

function contentHash(paths: string[]) {
	const hash = createHash("sha256");
	for (const path of paths) {
		hash.update(readFileSync(path));
	}
	return hash.digest("hex").slice(0, 16);
}

function writeupSourceFiles() {
	const directory = resolveFromRoot("../src/writeups/");
	if (!existsSync(directory)) {
		return [];
	}
	return readdirSync(directory, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map((entry) => `${directory}${entry.name}/index.mdx`)
		.filter((path) => existsSync(path));
}

// The CV PDF embeds the technical-writing list, so the writeups count too.
function cvContentHashSourceFiles() {
	const cvPage = resolveFromRoot("../src/pages/cv.astro");
	return [
		...(existsSync(cvPage) ? [cvPage] : []),
		...writeupSourceFiles(),
	];
}

async function main(): Promise<void> {
	const cvContentHash = contentHash(cvContentHashSourceFiles());
	const ogTemplateHash = contentHash([
		resolveFromRoot("../src/components/og-template.tsx"),
	]);

	const contents = `// Generated by scripts/generate-content-hashes.ts — do not edit by hand.
export const CV_CONTENT_HASH = "${cvContentHash}";
export const OG_TEMPLATE_HASH = "${ogTemplateHash}";
`;

	await writeFile(OUTPUT_PATH, contents);
	stdout.write(`Generated ${relative(process.cwd(), OUTPUT_PATH)}\n`);
}

main().catch((error: unknown) => {
	const message = error instanceof Error ? error.message : "Unknown error";
	process.stderr.write(`${message}\n`);
	process.exitCode = 1;
});
