/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicalWriteupsIndexRouteImport } from './routes/technical-writeups/index'
import { Route as TechnicalWriteupsSlugRouteImport } from './routes/technical-writeups/$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalWriteupsIndexRoute = TechnicalWriteupsIndexRouteImport.update({
  id: '/technical-writeups/',
  path: '/technical-writeups/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalWriteupsSlugRoute = TechnicalWriteupsSlugRouteImport.update({
  id: '/technical-writeups/$slug',
  path: '/technical-writeups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/work': typeof WorkRoute
  '/technical-writeups/$slug': typeof TechnicalWriteupsSlugRoute
  '/technical-writeups/': typeof TechnicalWriteupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/work': typeof WorkRoute
  '/technical-writeups/$slug': typeof TechnicalWriteupsSlugRoute
  '/technical-writeups': typeof TechnicalWriteupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/work': typeof WorkRoute
  '/technical-writeups/$slug': typeof TechnicalWriteupsSlugRoute
  '/technical-writeups/': typeof TechnicalWriteupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/work'
    | '/technical-writeups/$slug'
    | '/technical-writeups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/work'
    | '/technical-writeups/$slug'
    | '/technical-writeups'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/work'
    | '/technical-writeups/$slug'
    | '/technical-writeups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  WorkRoute: typeof WorkRoute
  TechnicalWriteupsSlugRoute: typeof TechnicalWriteupsSlugRoute
  TechnicalWriteupsIndexRoute: typeof TechnicalWriteupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-writeups/': {
      id: '/technical-writeups/'
      path: '/technical-writeups'
      fullPath: '/technical-writeups/'
      preLoaderRoute: typeof TechnicalWriteupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-writeups/$slug': {
      id: '/technical-writeups/$slug'
      path: '/technical-writeups/$slug'
      fullPath: '/technical-writeups/$slug'
      preLoaderRoute: typeof TechnicalWriteupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  WorkRoute: WorkRoute,
  TechnicalWriteupsSlugRoute: TechnicalWriteupsSlugRoute,
  TechnicalWriteupsIndexRoute: TechnicalWriteupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
